// <auto-generated />
using System;
using BasketballAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasketballAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528211706_PersonIdNullable")]
    partial class PersonIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasketballAPI.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Assists")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Blocks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FieldGoalsAttempted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FieldGoalsMade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FieldGoalsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FoulsPersonal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreeThrowsAttempted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreeThrowsMade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreeThrowsPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GameDateTimeEst")
                        .HasColumnType("datetime2");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameSubLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Home")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NumMinutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpponentTeamCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpponentTeamId")
                        .HasColumnType("int");

                    b.Property<string>("OpponentTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTeamCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerTeamId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PlusMinusPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReboundsDefensive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReboundsOffensive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReboundsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SeriesGameNumber")
                        .HasColumnType("int");

                    b.Property<string>("StartingPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Steals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThreePointersAttempted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThreePointersMade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThreePointersPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Turnovers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Win")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerGameStats");
                });
#pragma warning restore 612, 618
        }
    }
}
